sudo: false
language: csharp
solution: solution-name.sln
install:
  - nuget restore TDD-Katas-project.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TDD-Katas-project.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Release/TDD-Katas-project.dll
